name: Sync Fork

on:
  schedule:
    - cron: '*/720 * * * *' # every 12 hours
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: ViCCo-Group
          base: master
          head: master
